version: '3.9'
services:
    php-apache: 
        image: webdevops/php-apache:7.3
        container_name: php-apache-container
        volumes:
            - ./:/app
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
            - "8888:80"
        depends_on:
            - db
        networks:
            - producao
    db:     
        image: postgres
        container_name: "banco"
        environment:
            POSTGRES_USER: aba
            POSTGRES_PASSWORD: "1234"
        networks:
            - producao
        ports:
            - "5432:5432"
        volumes:
            - ./vol/db:/var/lib/postgresql/data
networks:
    producao:
        driver: bridge
