version: '3.9'
services:
    php-apache: 
        image: webdevops/php-apache:7.3
        container_name: php-apache-container
        volumes:
            - ./:/app
        ports:
            - "8888:80"
        depends_on:
            - db
        networks:
            - producao
    db:     
        image: postgres
        container_name: "banco"
        environment:
            POSTGRES_USER: aba
            POSTGRES_PASSWORD: "1234"
        networks:
            - producao
        ports:
            - "5432:5432"
        volumes:
            - ./vol/db:/var/lib/postgresql/data
    php-fpm:
        build: docker/xdebug/php-fpm
        working_dir: /application
        volumes:
            - './docker/xdebug/application:/application'
            - './docker/xdebug/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
        environment:
            XDEBUG_CONFIG: remote_host=localhost #docker network ip.
            PHP_IDE_CONFIG: "serverName=xdebug-docker" #phpstorm variavel de ambiente com o nome do server configurado.
networks:
    producao:
        driver: bridge
