version: '3'
services:
    php-apache:
        build:
            dockerfile: ./docker/phpapache.dockerfile
            context: .
        image: bigcouve/phpapache
        container_name: php-apache-1
        ports:
            - "8888:80"
        networks:
            - producao
    db:
        image: postgres
        restart: always
        container_name: postgresha
        environment:
            POSTGRES_PASSWORD: root
        networks:
            - producao
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-container
        ports:
            - "5712:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "doug@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "1234"
        depends_on:
            - db
        networks:
            - producao
    adminer:
        image: adminer
        restart: always
        ports:
            - 800:8080
        networks:
            - producao
    

networks:
    producao:
        driver: bridge