version: '3.9'
services:
    php-apache:
        build:
            dockerfile: ./docker/phpapache.dockerfile
            context: .
        image: bigcouve/phpapache
        container_name: php-apache-1
        ports:
            - "8888:80"
        networks:
            - producao
        depends_on: 
            - db
    db:
        image: postgres:12.6
        container_name: "banco"
        environment:
            POSTGRES_USER: aba
            POSTGRES_PASSWORD: "1234"
        networks:
            - producao
        ports:
            - "5432:5432"
        volumes:
            - ./vol/db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-container
        ports:
            - "81:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "a@gmail.com" 
            PGADMIN_DEFAULT_PASSWORD: "1234"
        depends_on:
            - db
        networks:
            - producao
networks:
    producao:
        driver: bridge
